name: Test
on: [push]

jobs:
  test:
    name: Test with base image python:${{ matrix.base_image }}
    strategy:
      matrix:
        base_image:
          - latest
          - slim
          - alpine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Run tests
        run: cd tests && sudo IMAGE_TAG="${{ matrix.base_image }}" bash test.sh
